name: Running the collector script on test environment

on: [pull_request]

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps: 

      - name: Checking out the securicad-azure-collector branch
        uses: actions/checkout@v2
        with:
          repository: foreseeti/securicad-azure-collector
          token: ${{ secrets.GITHUB_TOKEN }}
          path: securicad-azure-collector

      - run: |
          cd securicad-azure-collector
          export AZURE_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}
          export AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}
          export AZURE_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}
          export AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
          pip3 install -r requirements.txt
          mkdir -p environment_files
          python3 fetch_subscription_resources.py -D
